my_blog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('website.urls', namespace='website')),
]

website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [

    path('', views.index, name='index'),
    path('projects', views.projects, name='projects'),
    path('contact', views.projects, name='contact'),
]

website/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

website/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'website/index.html')


def projects(request):
    return render(request, 'website/projects.html')

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>vini-codex</title>
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta
        name="description"
        content="Vini is a full-stack dev web developer who specializes Python and Javascript frameworks"
    />
    <meta name="robots" content="index,follow" />
    <link
        href="https://fonts.googleapis.com/css?family=Montserrat:400,500&display=swap"
        rel="stylesheet"
    />
</head>
    {% block content %}
    {% endblock %}
</html>

website/templates/website/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>vini-codex</title>
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta
        name="description"
        content="Vini is a full-stack dev web developer who specializes Python and Javascript frameworks"
    />
    <meta name="robots" content="index,follow" />
    <link
        href="https://fonts.googleapis.com/css?family=Montserrat:400,500&display=swap"
        rel="stylesheet"
    />
</head>
    {% block content %}
    {% endblock %}
<footer>
      <h4>vinicodex &copy; 2018</h4>
      <ul>
        <li>
          <a href="#"
            ><img src="{% static 'icons/twitter 1.svg' %}" alt="twitter-social"
          /></a>
        </li>
        <li>
          <a href="#"
            ><img src="{% static 'icons/instagram 1.svg' %}" alt="instagram-social"
          /></a>
        </li>
        <li>
          <a href="#"
            ><img src="{% static 'icons/youtube-symbol 1.svg' %}" alt="youtube-social"
          /></a>
        </li>
      </ul>
</footer>
</html>

website/templates/website/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

website/templates/website/projects.html
{% extends "website/post/../base.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}
    <header class="main-head">
      <nav>
        <div class="logo">
          <img src="../icons/code.svg" alt="logo" />
          <h1>Dev Ed</h1>
        </div>
        <ul>
          <li><a href="{% url 'website:index' %}">Home</a></li>
        </ul>
      </nav>
    </header>
    <section class="projects">
      <div class="travelly">
        <h2>Travelly</h2>
        <img src="../img/travelly.jpg" alt="travelly-project" />
      </div>
      <div class="travelly">
        <h2>Elena Joy</h2>
        <img src="../img/elena-joy.jpg" alt="elena-project" />
      </div>
    </section>
{% endblock %}